FROM python:3.10 as builder

COPY requirements.txt /

RUN pip wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt -i https://pypi.douban.com/simple

FROM python:3.10

ENV APP_HOME=/home/app

RUN mkdir -p $APP_HOME

WORKDIR $APP_HOME

COPY --from=builder /wheels /wheels

COPY . $APP_HOME

RUN pip install --no-cache /wheels/*

RUN make github_install

CMD ["make","build"]

